package markdown

import (
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/image/draw"
)

// buildCSS returns the complete stylesheet string injected into every chapter
// via the book's FDST CSS flow record. It consists of built-in Kindle-tuned
// defaults followed by any custom CSS supplied through [WithCustomCSS].
//
// Design decisions driven by the MobileRead MOBI/KF8 specification:
//   - font-family and font-size are NOT set on body (reader's preference)
//   - text-align is NOT forced on body (reader's preference)
//   - left margins use 1em increments (spec limitation)
//   - padding-left is avoided; margin-left is used instead (kindlegen ignores padding-left)
//   - @media amzn-kf8 scopes KF8-only rules
//   - @media amzn-mobi and (monochrome) provides fallback for grey text on e-ink
func buildCSS(custom string) string {
	const base = `
/* github.com/dsparkman/mobi default stylesheet — Kindle KF8 tuned */

/* Box model reset. Do NOT reset font-size or font-family. */
* { margin: 0; padding: 0; }

/* Body: line-height only. Font and size are the reader's choice. */
body { line-height: 1.5; }

/* Headings */
h1, h2, h3, h4, h5, h6 {
    font-weight: bold;
    page-break-after: avoid;
    margin-top: 1em;
    margin-bottom: 0.5em;
}
h1 { font-size: 1.6em; }
h2 { font-size: 1.4em; }
h3 { font-size: 1.2em; }
h4, h5, h6 { font-size: 1em; }

/* Paragraphs */
p { margin-bottom: 0.8em; }

/* Blockquotes: 1em left margin per spec; no right margin increase. */
blockquote {
    margin-left: 1em;
    margin-right: 0;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    font-style: italic;
}

/* Code blocks */
pre {
    margin: 0.5em 0;
    white-space: pre-wrap;
    word-wrap: break-word;
}
code, pre code {
    font-family: monospace;
    font-size: 0.9em;
}

/* Lists: 2em per nesting level. */
ul, ol { margin-left: 2em; margin-bottom: 0.5em; }
li      { margin-bottom: 0.2em; }

/* Links: inherit colour so the reader's chosen theme applies. */
a { color: inherit; text-decoration: underline; }

/* Images: never overflow the viewport. */
img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 0.5em auto;
}

/* Tables (class added by sanitizeForKindle). */
.md-table {
    border-collapse: collapse;
    width: 100%;
    margin: 0.5em 0;
    font-size: 0.9em;
}
.md-table th,
.md-table td {
    border: 1px solid;
    padding: 0.3em 0.5em;
    text-align: left;
}
.md-table th { font-weight: bold; }

/* Horizontal rule */
hr { border: none; border-top: 1px solid; margin: 1em 0; }

/* Footnotes (generated by gomarkdown). */
.footnotes { font-size: 0.85em; margin-top: 2em; }
.footnotes hr { margin-bottom: 0.5em; }

/* Explicit page break utility class. */
.page-break { page-break-after: always; }

/* Grey text: fall back to black on monochrome e-ink displays. */
.muted, .grey { color: #666; }
@media amzn-mobi and (monochrome) {
    .muted, .grey { color: black; }
}

/* KF8-only refinements. */
@media amzn-kf8 {
    p { margin-bottom: 0.8em; }
}
`
	if custom == "" {
		return base
	}
	return base + "\n/* Custom CSS (via WithCustomCSS) */\n" + custom
}

// loadAndScaleCover opens the image at imagePath, decodes it, and returns
// both the full-resolution cover and a thumbnail scaled to fit within
// 330×500 pixels while preserving aspect ratio.
//
// imagePath is resolved relative to baseDir when it is a relative path.
// Supported formats: JPEG (.jpg/.jpeg), PNG (.png), GIF (.gif).
//
// The thumbnail is produced with BiLinear interpolation from
// [golang.org/x/image/draw] for good quality at low cost. If the source
// image already fits within 330×500, it is returned unchanged as the thumbnail.
func loadAndScaleCover(imagePath, baseDir string) (cover, thumb image.Image, err error) {
	if !filepath.IsAbs(imagePath) && baseDir != "" {
		imagePath = filepath.Join(baseDir, imagePath)
	}

	ext := strings.ToLower(filepath.Ext(imagePath))
	switch ext {
	case ".jpg", ".jpeg", ".png", ".gif":
	default:
		return nil, nil, fmt.Errorf("unsupported cover format %q (use jpg, png, or gif)", ext)
	}

	f, err := os.Open(imagePath)
	if err != nil {
		return nil, nil, fmt.Errorf("open %q: %w", imagePath, err)
	}
	defer func() { _ = f.Close() }()

	cover, _, err = image.Decode(f)
	if err != nil {
		return nil, nil, fmt.Errorf("decode %q: %w", imagePath, err)
	}

	thumb = scaleTo(cover, 330, 500)
	return cover, thumb, nil
}

// scaleTo returns img scaled to fit within maxW×maxH, preserving aspect ratio.
// Scaling uses BiLinear interpolation from [golang.org/x/image/draw].
// If img already fits, it is returned unchanged.
func scaleTo(src image.Image, maxW, maxH int) image.Image {
	b := src.Bounds()
	w, h := b.Dx(), b.Dy()
	if w <= maxW && h <= maxH {
		return src
	}

	scale := min(float64(maxW)/float64(w), float64(maxH)/float64(h))
	newW := int(float64(w) * scale)
	newH := int(float64(h) * scale)

	dst := image.NewRGBA(image.Rect(0, 0, newW, newH))
	draw.BiLinear.Scale(dst, dst.Bounds(), src, b, draw.Over, nil)
	return dst
}

